# Mock Moody's API Configuration
mock_behavior:
  # Latency simulation (seconds)
  min_latency: 0.1
  max_latency: 0.5
  
  # Error rates (0.0 to 1.0)
  rate_limit_error_rate: 0.05  # 5%
  service_unavailable_rate: 0.02  # 2%
  internal_error_rate: 0.01  # 1%
  
  # State transitions
  state_progression:
    submitted_to_queued_polls: 1
    queued_to_running_polls: 2
    running_to_complete_polls: 4
    
  # Success rates
  queued_to_running_success_rate: 0.9  # 90%
  running_to_complete_success_rate: 0.8  # 80%
  
  # Progress increments
  min_progress_increment: 10
  max_progress_increment: 25