analysis:
  name: "Q1 2024 Risk Analysis"
  description: "Quarterly risk assessment for US portfolio"
  configurations:
    - name: "US Earthquake High Resolution"
      model: "EQ_US_HR_v2"
      parameters:
        exposure_set: "us_portfolio_2024"
        event_set: "stochastic_10k"
        resolution: "high"
        deductible: 100000
        
    - name: "US Earthquake Standard"
      model: "EQ_US_STD_v2"
      parameters:
        exposure_set: "us_portfolio_2024"
        event_set: "historical"
        resolution: "standard"
        deductible: 100000
        
    - name: "US Hurricane Atlantic"
      model: "HU_US_ATL_v3"
      parameters:
        exposure_set: "us_portfolio_2024"
        event_set: "stochastic_50k"
        storm_surge: true
        demand_surge: 1.15
        
    - name: "US Flood FEMA Zones"
      model: "FL_US_FEMA_v1"
      parameters:
        exposure_set: "us_portfolio_2024"
        flood_zones: ["A", "AE", "V", "VE"]
        include_pluvial: true